<?php
include("includes/connection.php");
include("includes/function.php");

include("includes/perm.php");
?>
<!DOCTYPE html>
<html>

<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>BENSO GARMENTING - Cost Generation List</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="vendors/images/favicon-16x16.png">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="src/plugins/datatables/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="src/plugins/datatables/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="vendors/styles/style.css">

    <!-- sweetalert -->
    <link rel="stylesheet" type="text/css" href="src/plugins/sweetalert2/sweetalert2.css">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>

<body>

    <?php
    include('includes/header.php');
    include('includes/sidebar.php');
    ?>

    <div class="main-container nw-cont">
        <?php
        if ($_SESSION['msg'] == 'updated') { ?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success!</strong> Updated.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
        <?php } else if ($_SESSION['msg'] == 'added') { ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success!</strong> Saved.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
        <?php }
        $_SESSION['msg'] = '';
        ?>
        <div class="pd-ltr-20 xs-pd-20-10">
            <div class="min-height-200px">

                <!-- Export Datatable start -->
                <div class="card-box mb-30">
                    <?php if(COST_GENERATION!=1) { action_denied(); exit; } ?>
                    <div class="pd-20">
                        <?php if(COST_GENERATION_ADD==1) { ?>
                            <a class="btn btn-outline-primary" href="new-costing.php" style="float: right;"><i class="fa fa-plus" aria-hidden="true"></i> New Costing</a>
                        <?php } ?>
                    </div>
                    <div class="pd-20">
                        <h4 class="text-blue h4">Cost Generation List</h4>
                    </div>
                    <div class="pb-20">
                        <table class="table hover data-table-export nowrap">
                            <thead>
                                <tr>
                                    <th>Sl.No</th>
                                    <th>Entry Number</th>
                                    <th>Cost Generation Date</th>
                                    <th>Cost Generated By</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $x=1;
                                
                                $nqy = "SELECT a.id, a.entry_number, b.cg_name, a.is_receipted, a.created_date, a.created_by ";
                                $nqy .= " FROM cost_generation a ";
                                $nqy .= " LEFT JOIN employee_detail b ON a.employee = b.id ";
                                $nqy .= " ORDER BY a.id DESC ";
                                
                                $qry = mysqli_query($mysqli, $nqy);
                                while($row = mysqli_fetch_array($qry)) {
                                ?>
                                    <tr>
                                        <td><?= $x; ?></td>
                                        <td><?= $row['entry_number']; ?></td>
                                        <td><?= date('d-m-Y', strtotime($row['created_date'])); ?></td>
                                        <td><?= employee_name($row['created_by']); ?></td>
                                        <td>
                                            <div class="dropdown">
                                                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle"
                                                    role="button" data-toggle="dropdown">
                                                    <i class="dw dw-more"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                                    
                                                    <!--<a class="dropdown-item" onclick="confirmCreate(<?= $row['style_id']; ?>)"> <i class="icon-copy ion-ios-chatbubble-outline"></i> Create </a>-->
                                                            
                                                    <?php if(COST_GENERATION_VIEW==1) { ?>
                                                        <a class="dropdown-item" data-id="<?= $sql['id']; ?>" href="new-costing.php?&typ=view&id=<?= $row['id'] ?>"><i class="fa fa-eye"></i> View</a>
                                                    <?php } if($row['is_receipted'] != 'yes') { if(COST_GENERATION_EDIT==1) { ?>
                                                        <!-- <a class="dropdown-item" data-id="<?= $sql['id']; ?>" href="new-costing.php?&typ=edit&id=<?= $row['id'] ?>"><i class="dw dw-edit2"></i> Edit</a> -->
                                                    <?php } if(COST_GENERATION_DELETE==1) { ?>
                                                        <a class="dropdown-item" data-id="<?= $sql['id']; ?>" onclick="(<?= $row['id'] ?>)"><i class="fa fa-trash"></i> Delete</a>
                                                    <?php } } ?>
                                                    <!--<a class="dropdown-item" href="so_print.php?id=<?= $sql['id'] ?>" target="_blank"> <i class="icon-copy fa fa-print" aria-hidden="true"></i> Print</a>-->
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                <?php $x++; } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- Export Datatable End -->
            </div>
            <?php include('includes/footer.php'); include('modals.php'); ?>
        </div>
    </div>

    <!-- js -->
    <?php include('includes/end_scripts.php'); ?>
    
    
    <script>
        function confirmCreate(id) {
            swal({
                title: 'Are you sure?',
                text: "Confirm Create Bill!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, Create!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success margin-5',
                cancelButtonClass: 'btn btn-danger margin-5',
                buttonsStyling: false
            }).then(function (dd) {
                if (dd['value'] == true) {
                    $.ajax({
                        type: 'POST',
                        url: 'ajax_action.php?confirmCreate=1&id=' + id,
                        success: function (msg) {
                            if (msg == 1) {
                                swal({
                                    type: 'success',
                                    title: 'Bill Created',
                                    showConfirmButton: true,
                                    timer: 1500
                                }).then(
                                    function () {
                                        location.reload();
                                    })
                            } else {
                                swal(
                                    'Something went wrong',
                                    '',
                                    'error'
                                )
                            }
                        }
                    })
                } else {
                    swal(
                        'Cancelled',
                        '',
                        'error'
                    )
                }
            })
        }
    </script>

</body>

</html>